### ISSUE TITLE
cli: Make querying a pool show reserve amounts

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/liquidity#430]
## Summary of Bug

Currently when you query a pool `gaiad q liquidity pool 1`, you get a result of the form:

```
- id: "1"
  pool_coin_denom: poolDFB8434D5A80B4EAFA94B6878BD5B85265AC6C5D37204AB899B1C3C52543DA7E
  reserve_account_address: cosmos1m7uyxn26sz6w4755k6rch4dc2fj6cmzajkszvn
  reserve_coin_denoms:
  - ibc/14F9BC3E44B8A9C1BE1FB08980FAB87034C9905EF17CF2F5008FC085218811CC
  - uatom
  type_id: 1
```

If you want to find the reserve assets / implied spot price of a pool, the only way per my understanding is to then do `gaiad q bank balances {copied reserve_account_address}`.

I suggest making querying already return this when you query an individual pool. (`gaiad q liquidity pool {pool_ID}`)

## Version

Whats used on the hub.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
